#!/usr/bin/env bash
# echo it's subdomains with type of record name

domain_info () {
    record_with_ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $record_with_ip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ $# -eq 1 ]
then
   domain_info "$1" "www"
   domain_info "$1" "lb-01"
   domain_info "$1" "web-01"
   domain_info "$1" "web-02"
elif [ $# -eq 2 ]
then
     domain_info "$1" "$2"
fi
