#!/usr/bin/env bash
# echo it's subdomains with type of record name

domain_info () {
    record_with_ip=$(dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$1 $record_with_ip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ $# -eq 1 ]
then
   domain_info "www" "$1"
   domain_info "lb-01" "$1"
   domain_info "web-01" "$1"
   domain_info "web-02" "$1"
elif [ $# -eq 2 ]
then
     domain_info "$2" "$1"
fi
