#!/usr/bin/env bash
# install nginx
apt install -y nginx


echo "Hello World!" > /var/www/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

if pgrep nginx > /dev/null
then
    nginx -s reload
else
    nginx
fi
