#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location	 /redirect_me {
         return 301 https://www.youtube.com/watch?v=AfIOBLr1NDU;
     }
}
" > /etc/nginx/sites-available/default

if pgrep nginx > /dev/null
then
    nginx -s reload
else
    nginx
fi
