#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

sed -i '/server_name _;/a \\n        location /redirect_me {\n                 return 301 https://google.com;\n    }\
' /etc/nginx/sites-available/default

if pgrep nginx > /dev/null
then
    nginx -s reload
else
    nginx
fi
