#!/usr/bin/env bash
# install nginx on server
apt install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

# create index.html with hello world in it
echo "Hello World!" > /etc/nginx/html/index.html

touch /etc/nginx/html/404.html

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# modify nginx confi
sed -i "s/80 default_server;/80;/g" /etc/nginx/sites-available/default

# add redirection for /redirect_me
sed -i '/server_name _;/a \\n        location /redirect_me {\n                 return 301 https://www.youtube.com/watch?v=AfIOBLr1NDU;\n    }' /etc/nginx/sites-available/default

# add 404 page handler
sed -i '/server_name _;/a \\n        error_page 404 /404.html; \n        location /404 {\n                 root /etc/nginx/html;\n                 internal; \n    }' /etc/nginx/sites-available/default


# check if nginx is running
if pgrep nginx > /dev/null; then
    # reload nginx confi
    nginx -s reload
else
    # start nginx
    nginx
fi
