#!/usr/bin/env bash
# install nginx web server and add custom header

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
       listen	  80 default_server;
       listen	  [::]:80 default_server;
       root	  /etc/nginx/html;
       add-header X-Served-By $HOSTNAME
       index	  index.html index.htm;

       location /redirect_me {
       		return 301 https://youtube.com;
	}

	error_page 404 /404.html;
	location /404 {
		 root /etc/nginx/html;
		 internal;
	}
}
" > /etc/nginx/sites-available/default

service nginx restart
