#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 4306-web-01 54.234.16.12:80 check
    server 4306-web-02 107.23.106.236:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start