#!/usr/bin/env bash
# install haproxy load balancer and configure it to the requirement
# Enable dedicated PPA
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update

# Install HAProxy load balancer
apt-get install -y haproxy=2.8.*

echo "ENABLED=1" >> /etc/default/haproxy
# Backup original haproxy.cfg file with added .original extension
mv /etc/haproxy/haproxy.cfg{,.original}

# Create new haproxy.cfg file
touch /etc/haproxy/haproxy.cfg

# Define content for haproxy.cfg
config_content=$(cat <<EOF
# Global section
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

# Defaults section
defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

listen http_server
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 4306-web-01 54.210.57.42:80 check
    server 4306-web-02 54.90.60.225:80 check
EOF
)

echo "$config_content" > /etc/haproxy/haproxy.cfg

service haproxy start
