#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <API KEY> <APPLICATION KEY>"
    exit 1
else
    curl -X GET "https://api.datadoghq.com/api/v1/dashboard" \
    -H "Content-Type: application/json" \
    -H "DD-API-KEY: $1" \
    -H "DD-APPLICATION-KEY: $2"
fi
