#!/usr/bin/env bash
# This script will accept a IP address as an arguemnt and ping 5 times

if [ "$#" -eq 0 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
