#!/usr/bin/env bash
# This script displays the PID along with the process name of processes
#+ whose name contain the word bash

# Use pgrep to find all processes containing the word "bash"
pids=$(pgrep -d ' ' -f bash)

for pid in $pids
do
    name=$(grep -w "Name:" /proc/$pid/status | cut -d ":" -f2)
    echo "$pid $name"
done
