#!/usr/bin/env bash
# This script displays the PID along with the process name of processes
#+ whose name contain the word bash

# Use pgrep to find all processes containing the word "bash"
pgrep bash -l
