#!/usr/bin/env bash
# This script sisplays numbers from 1 to 100 if the number is divisible by 3
#+ it will print Fizz if the number is divisible by 5 it print Buzz
#+ if the number is both divisible by 3 and 5 it will print FizzBuzz

i=1
until [ $i -eq 101 ]
do
    if (( i % 3 == 0 )) && (( i % 5 == 0 ))
    then
	echo "FizzBuzz"
    elif (( i % 3 == 0 ))
    then
	echo "Fizz"
    elif (( i % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo "$i"
    fi
    i=$(( i + 1 ))
done
