#!/usr/bin/env bash
# This script echo "Best School" and echo "bad luck" in 4th iteration
#+ "good luck" in 8th loop iteration

i=1
while [ "$i" -lt 11 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    i=$(( i+1 ))
done
