#!/usr/bin/env bash
# This script display hours from 0 to 12 and display minutes from 1 to 59

i=0
while [ "$i" -lt 12 ]
do
    x=1
    echo "Hour: $i"
    while [ "$x" -lt 60 ]
    do
	echo "$x"
	x=$(( x+1 ))
    done
    i=$(( i+1 ))
done
