#!/usr/bin/env bash
# script that configure an Ubuntu server
cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2\tlocalhost" > /etc/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts.new
cp -f ~/hosts.new /etc/hosts
